config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[create index] do
        collection do
          post 'login-as-visitor'
          post 'login-via-gaas-token'
          get 'me-via-gaas-token'
        end
      end
      get 'me', to: 'users#show'
      resource :preferences, only: %i[show update]

      resources :rooms, only: %i[index show create update] do
        member do
          get 'knock-knock', to: 'rooms#knock_knock'
          post 'close', to: 'rooms#destroy'
          post 'game', to: 'games#create'
          delete 'game', to: 'games#destroy'
          post 'game/split', to: 'games#split'
          post 'game/play-unit', to: 'games#play'

          # TODO: will be deprecated
          post 'ai_players', to: 'rooms#bots'

          post 'bots', to: 'rooms#bots'
        end
      end
      resources :games, only: %i[show destroy create] do
        member do
          post 'end-game-via-gaas-token'

          post 'init-map-automatically', to: 'games#init_map_automatically'
          post 'reset-game', to: 'games#reset_game'

          post 'place-stack-automatically', to: 'games#random_place_stack'
          post 'place-stack', to: 'games#place_stack'

          post 'split-stack-automatically', to: 'games#random_split_stack'
          post 'split-stack', to: 'games#split_stack'
        end
      end
      resources :bots, only: %i[create index update destroy show]
    end
  end

  resources :games
  resources :rooms do
    member do
      put :join
      delete :leave
      post :play
    end
  end
  get 'home/index'
  resources :visitors
  get '/login', to: 'sessions#new', as: 'new_user_session'
  post '/login', to: 'sessions#create', as: 'user_session'
  delete '/logout', to: 'sessions#destroy', as: 'destroy_user_session'

  root 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  has_secure_password

  has_one :visitors_room, dependent: :destroy
  has_one :room, through: :visitors_room
  belongs_to :bot, optional: true

  validates :name, presence: true, uniqueness: true
  validate :allow_preferences_attributes?

  enum :role, {
    admin: 0,
    user: 1,
    guest: 2,
    ai: 3,
    test_dummy: 4
  }, prefix: true

  def encode_jwt
    payload = { sub: id }
    Api::JsonWebToken.encode payload
  end

  ALLOW_PREFERENCES = %w[nickname].freeze

  def allow_preferences_attributes?
    return true if preferences.blank?

    preferences.keys.all? { |key| ALLOW_PREFERENCES.include?(key) }
  end

  def read_preferences
    self.preferences ||= {}
    ALLOW_PREFERENCES.each_with_object({}) do |key, hash|
      hash[key] = preferences[key] || 'none'
    end
  end

  def nickname
    return bot&.name || 'none' if role_ai?

    self.preferences&.dig('nickname') || 'none'
  end

  # delegate 'ready?', to: :visitors_room,  allow_nil: true

  def ready?
    visitors_room&.ready? || false
  end

  def ready!
    visitors_room&.ready!
  end

  def unready!
    visitors_room&.unready!
  end

  def character
    visitors_room&.character
  end

  def character=(value)
    visitors_room&.update(character: value)
  end

  def owner_of?(room)
    room.owner_id == id
  end

  def knock_knock(room)
    payload = { sub: room.id }
    Api::JsonWebToken.encode payload, 10.seconds.from_now
  end

  class << self
    def new_visitor(name: nil, password: nil, role: nil)
      create!(
        name: name || "guest_#{Time.now.strftime('%Y%m%d')}_#{SecureRandom.alphanumeric(10)}",
        password: password || SecureRandom.alphanumeric(16),
        role: role || :guest
      )
    end
  end

  delegate :id, :name, to: :room, prefix: true, allow_nil: true
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: %i[ show edit update destroy ]

  # GET /visitors or /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    @visitor.destroy!

    respond_to do |format|
      format.html { redirect_to visitors_url, notice: "Visitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:name, :password_digest)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_with(model: visitor, class: "contents") do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/visitors/_visitor.html.erb
<div id="<%= dom_id visitor %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= visitor.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Password digest:</strong>
    <%= visitor.password_digest %>
  </p>

</div>

app/views/visitors/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing visitor</h1>

  <%= render "form", visitor: @visitor %>

  <%= link_to "Show this visitor", @visitor, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to visitors", visitors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/visitors/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-5">
    <%= link_to 'Home', root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
  </div>

  <% content_for :title, "Visitors" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Visitors</h1>
    <%= link_to "New visitor", new_visitor_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="visitors" class="min-w-full">
    <% @visitors.each do |visitor| %>
      <%= render visitor %>
      <p>
        <%= link_to "Show this visitor", visitor, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/visitors/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New visitor</h1>

  <%= render "form", visitor: @visitor %>

  <%= link_to "Back to visitors", visitors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/visitors/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @visitor %>

    <%= link_to "Edit this visitor", edit_visitor_path(@visitor), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to visitors", visitors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this visitor", @visitor, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>