config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[create index] do
        collection do
          post 'login-as-visitor'
          post 'login-via-gaas-token'
          get 'me-via-gaas-token'
        end
      end
      get 'me', to: 'users#show'
      resource :preferences, only: %i[show update]

      resources :rooms, only: %i[index show create update] do
        member do
          get 'knock-knock', to: 'rooms#knock_knock'
          post 'close', to: 'rooms#destroy'
          post 'game', to: 'games#create'
          delete 'game', to: 'games#destroy'
          post 'game/split', to: 'games#split'
          post 'game/play-unit', to: 'games#play'

          # TODO: will be deprecated
          post 'ai_players', to: 'rooms#bots'

          post 'bots', to: 'rooms#bots'
        end
      end
      resources :games, only: %i[show destroy create] do
        member do
          post 'end-game-via-gaas-token'

          post 'init-map-automatically', to: 'games#init_map_automatically'
          post 'reset-game', to: 'games#reset_game'

          post 'place-stack-automatically', to: 'games#random_place_stack'
          post 'place-stack', to: 'games#place_stack'

          post 'split-stack-automatically', to: 'games#random_split_stack'
          post 'split-stack', to: 'games#split_stack'
        end
      end
      resources :bots, only: %i[create index update destroy show]
    end
  end

  resources :games
  resources :rooms do
    member do
      put :join
      delete :leave
      post :play
    end
  end
  get 'home/index'
  resources :visitors
  get '/login', to: 'sessions#new', as: 'new_user_session'
  post '/login', to: 'sessions#create', as: 'user_session'
  delete '/logout', to: 'sessions#destroy', as: 'destroy_user_session'

  root 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :room
  has_many :steps, dependent: :destroy, class_name: 'GameStep'

  FLAG_AUTO_GENERATE_MAP_BY_SYSTEM = true

  def should_initialize_map_by_system?
    FLAG_AUTO_GENERATE_MAP_BY_SYSTEM
  end

  def current_player
    players[current_player_index]
  end

  # [ ]: Search where this method is used
  def close
    update!(is_finished: true)
  end

  def close_by(user: nil)
    Domain::SplitGame::Command::Close.new(game: self, invoker: user).call
    close
  end

  def on_going?
    !is_finished
  end

  def finished?
    is_finished
  end

  def game_phase
    if steps.empty?
      'build map'
    else
      steps.last.game_phase
    end
  end

  def valid_position?(params)
    # TODO: implement this method
    Rails.logger.info { 'todo: implement Game#valid_position?' }
    true

    # return false unless params[:x].is_a?(Integer) && params[:y].is_a?(Integer)
    # return false unless (0..2).cover?(params[:x]) && (0..2).cover?(params[:y])

    # steps.none? { |step| step['x'] == params[:x] && step['y'] == params[:y] }
  end

  def pastures
    if steps.empty?
      []
    else
      steps.last.pastures
    end
  end

  def new_step(step_type, params = {})
    Step.new(self, step_type:, **params).exec
  end

  def random_place_stack
    current_player_color = players[current_player_index]['color']

    Step::Play.new(
      self, destination_grid: {
        'x' => rand(5 + players.size),
        'y' => rand(5 + players.size),
        'stack' => {
          'color' => current_player_color
        }
      }
    ).exec
  end

  def place_stack(target_x:, target_y:)
    current_player_color = players[current_player_index]['color']

    Step::Play.new(
      self, destination_grid: {
        'x' => target_x,
        'y' => target_y,
        'stack' => {
          'color' => current_player_color
        }
      }
    ).exec
  end

  def random_split_stack
    current_player_color = players[current_player_index]['color']

    original_grid = pastures.select do |pasture|
      (pasture['stack']['color'] == current_player_color) &&
        pasture['stack']['amount'] > 1 &&
        !pasture['is_blocked']
    end.sample

    # return unless original_grid

    random_amount = (original_grid.present? ? rand(1...original_grid['stack']['amount']) : 1)

    Step::Split.new(
      self, original_grid:, destination_grid: {
        'x' => rand(5 + players.size),
        'y' => rand(5 + players.size),
        'stack' => {
          'color' => current_player_color,
          'amount' => random_amount
        }
      }
    ).exec
  end

  def split_stack(
    origin_x:, origin_y:,
    target_x:, target_y:,
    target_amount:
  )
    current_player_color = players[current_player_index]['color']

    original_grid = pastures.find do |pasture|
      (pasture['x'] == origin_x) && (pasture['y'] == origin_y)
    end

    errors.add(:base, 'The pasture is not found') and return self if original_grid.nil?

    if original_grid['stack']['color'] != current_player_color
      errors.add(:base, 'You can only split your own stack') and return self
    end

    if original_grid['is_blocked']
      Rails.logger.warn { "Origin pasture is blocked: #{original_grid}" }
      # show the neighbor pastures for debugging
      [[0, 1], [1, 0], [1, -1], [0, -1], [-1, 0], [-1, 1]].each do |dx, dy|
        neighbor = @previous_pastures.find do |pasture|
          pasture['x'] == original_grid['x'] + dx && pasture['y'] == original_grid['y'] + dy
        end
        Rails.logger.warn { "Neighbor pasture: #{neighbor}" } if neighbor
      end
      errors.add(:base, 'You can only split a stack in a non-blocked pasture') and return self
    end

    if original_grid['stack']['amount'] <= 1
      errors.add(:base, 'You can only split a stack with more than 1 sheep') and return self
    end

    # TODO: check path between original and target is continuous

    Step::Split.new(
      self,
      original_grid:,
      destination_grid: {
        'x' => target_x,
        'y' => target_y,
        'stack' => {
          'color' => current_player_color,
          'amount' => target_amount
        }
      }
    ).exec
  end

  def game_config
    Jbuilder.new do |json|
      json.players_number players.size
      json.players players do |player|
        json.id player['id']
        json.nickname player['nickname']
        json.color player['color']
        json.character player['character']
        json.role player['role']
      end
    end.attributes!
  end

  def game_data(step: nil)
    last_step = step ? steps.find_by(step_number: step) : steps.last
    return {} if last_step.nil?

    Jbuilder.new do |json|
      json.step last_step.step_number
      json.current_player_index current_player_index
      json.phase game_phase
      json.pastures pastures do |pasture|
        json.x pasture['x']
        json.y pasture['y']
        json.is_blocked pasture['is_blocked']
        json.stack do
          json.color pasture['stack']['color']
          json.amount pasture['stack']['amount']
        end
      end
    end.attributes!
  end

  def action
    return {} if steps.empty?

    steps.last.action
  end

  def initialize_map_by_system(seed: nil)
    Step::InitializeMapBySystem.new(self, seed:).exec
  end

  def pastures_of_player_color(color)
    pastures.select { |pasture| pasture['stack']['color'] == color }
  end

  private

  def calculate_current_player_index
    (created_at.to_i * 13 + 17) % players.size
  end
end

app/controllers/api/v1/games_controller.rb
module Api
  module V1
    class GamesController < BaseController
      require 'net/http'

      before_action :find_game,
                    only: %i[show destroy play split init_map_automatically reset_game
                             place_stack random_place_stack
                             random_split_stack]
      skip_before_action :load_jwt_request, only: %i[create end_game_via_gaas_token]

      # POST /api/v1/games
      # currently the api only used for game_as_a_service to start a game
      # it will create a room and return the room url
      def create
        # print auth info in request header
        Rails.logger.debug { "Authorization: #{request.headers['Authorization']}" }

        # parse params
        Rails.logger.info { "roomId: #{params['roomId']}" }
        players = params['players']
        Rails.logger.info { 'players is empty' } if players.empty?
        players.each do |player|
          Rails.logger.info { 'player' }
          Rails.logger.info { "id: #{player['id']}" }
          Rails.logger.info { "nickName: #{player['nickName']}" }
        end

        room = Room.create!(name: "#{params['players'][0]['nickName']}'s Room")

        # current_time = Time.now.to_i
        $redis.set("gaas_room_id_of:#{room.id}", params['roomId'])
        $redis.expire("gaas_room_id_of:#{room.id}", 60 * 60) # 1 hour

        Domain::CreateRoomEvent.new(room_id: room.id).dispatch

        render json: {
          url: "https://split-sheep-spt.zeabur.app/#/room/#{room.id}"
        }, status: :ok
      end

      # GET /api/v1/games/:id?step=0
      # 查詢目前遊戲狀態
      def show
        @step = params.key?(:step) ? params[:step].to_i : @game.steps.size

        render status: :ok
      end

      # DELETE /api/v1/rooms/:id/game
      # 結束遊戲
      def destroy
        return render json: { error: 'Game is already finished' }, status: :unprocessable_entity if @game.finished?

        @game.close
        render json: { game: @game }, status: :ok
      end

      # POST /api/v1/rooms/:id/game/play-unit
      # 放入棋子
      # params: { x: 0, y: 0 }
      def play
        return render json: { error: 'Game is already finished' }, status: :unprocessable_entity if @game.finished?

        unless @game.current_player['name'] == @user.name
          return render json: { error: 'Not your turn' },
                        status: :unprocessable_entity
        end
        if @game.steps.size >= @game.players.size
          # all players have played their pieces
          return render json: { error: 'All players have played their pieces' }, status: :unprocessable_entity
        end

        unless @game.valid_position?(params)
          return render json: { error: 'Invalid position' },
                        status: :unprocessable_entity
        end

        @game.steps << { x: params[:x], y: params[:y], color: @game.current_player['color'] }
        @game.current_player_index = (@game.current_player_index + 1) % @game.players.size
        @game.save!

        render json: { game: @game }, status: :ok
      end

      # POST /api/v1/rooms/:id/game/split
      # 分配棋子
      # params: { origin_x: 1, origin_y: 1, target_x: 0, target_y: 0, amount: 1 }
      def split
        return render json: { error: 'Game is already finished' }, status: :unprocessable_entity if @game.finished?

        unless @game.current_player['name'] == @user.name
          return render json: { error: 'Not your turn' },
                        status: :unprocessable_entity
        end
        unless @game.valid_position?(params)
          return render json: { error: 'Invalid position' },
                        status: :unprocessable_entity
        end

        return render json: { error: 'Invalid amount' }, status: :unprocessable_entity if params[:amount].to_i < 1

        @game.steps << {
          origin_x: params[:origin_x],
          origin_y: params[:origin_y],
          target_x: params[:target_x],
          target_y: params[:target_y],
          amount: params[:amount],
          color: @game.current_player['color']
        }
        @game.current_player_index = (@game.current_player_index + 1) % @game.players.size
        @game.save!

        render json: { game: @game }, status: :ok
      end

      # POST /api/v1/games/:id/place-stack
      def place_stack
        res = @game.place_stack(target_x: params[:target_x].to_i, target_y: params[:target_y].to_i)

        return render json: { error: res.errors.full_messages }, status: :unprocessable_entity if res.errors.any?

        Domain::GameStackPlacedEvent.new(game_id: @game.id).dispatch
        Domain::GameTurnStartedEvent.new(game_id: @game.id).dispatch

        render json: { message: 'Stack placed' }, status: :ok
      end

      # POST /api/v1/games/:id/split-stack
      def split_stack
        res = @game.split_stack(
          origin_x: params[:origin_x].to_i,
          origin_y: params[:origin_y].to_i,
          target_x: params[:target_x].to_i,
          target_y: params[:target_y].to_i,
          target_amount: params[:target_amount].to_i
        )

        return render json: { error: res.errors.full_messages }, status: :unprocessable_entity if res.errors.any?

        Domain::GameStackSplittedEvent.new(game_id: @game.id).dispatch

        if @game.reload.game_phase == 'game_over'
          @game.close
          Domain::GameEndEvent.new(game_id: @game.id).dispatch
        else
          Domain::GameTurnStartedEvent.new(game_id: @game.id).dispatch
        end

        render json: { message: 'Stack splitted' }, status: :ok
      end

      # development usage
      def init_map_automatically
        res = @game.initialize_map_by_system

        return render json: { error: res.errors.full_messages }, status: :unprocessable_entity if res.errors.any?

        Domain::GameInitializedEvent.new(game_id: @game.id).dispatch
        Domain::GameTurnStartedEvent.new(game_id: @game.id).dispatch

        render json: { message: 'Map initialized' }, status: :ok
      end

      def random_place_stack
        res = @game.random_place_stack

        return render json: { error: res.errors.full_messages }, status: :unprocessable_entity if res.errors.any?

        Domain::GameStackPlacedEvent.new(game_id: @game.id).dispatch
        Domain::GameTurnStartedEvent.new(game_id: @game.id).dispatch

        render json: { message: 'Stack placed' }, status: :ok
      end

      def random_split_stack
        res = @game.random_split_stack

        return render json: { error: res.errors.full_messages }, status: :unprocessable_entity if res.errors.any?

        Domain::GameStackSplittedEvent.new(game_id: @game.id).dispatch
        Domain::GameTurnStartedEvent.new(game_id: @game.id).dispatch

        render json: { message: 'Stack splitted' }, status: :ok
      end

      def reset_game
        @game.close
        Domain::GameEndEvent.new(game_id: @game.id).dispatch

        room = @game.room

        if room.players.size < 2
          return render json: {
            error: 'Need at least 2 players to start a new game'
          }, status: :unprocessable_entity
        end

        new_game_id = room.start_new_game.id
        Domain::GameCreatedEvent.new(game_id: @game.id, new_game_id:).dispatch

        render json: { message: 'Game reset' }, status: :ok
      end

      private

      def find_game
        @game = Game.find_by(id: params[:id])
        return render json: { error: 'Game not found' }, status: :not_found unless @game

        @game
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    # @game.destroy!

    @game.close

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:room_id, :is_finished, :players, :current_player, :steps)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, class: "contents") do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :room_id %>
    <%= form.text_field :room_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :is_finished %>
    <%= form.check_box :is_finished, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :players %>
    <%= form.text_field :players, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :current_player %>
    <%= form.text_field :current_player, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :steps %>
    <%= form.text_field :steps, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Room:</strong>
    <%= game.room_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Is finished:</strong>
    <%= game.is_finished %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Players:</strong>
    <% game.players.each do |player| %>
      <div class="list-item ml-5  marker:text-<%= player["color"] %>-500 text-3xl">
        <%= player["name"] %> - <%= player["color"] %> (#<%= player["id"] %>)
      </div>
    <% end %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Current player:</strong>
    <% game.current_player.tap do |player| %>
      <div class="list-item ml-5  marker:text-<%= player["color"] %>-500 text-3xl">
        <%= player["name"] %> - <%= player["color"] %> (#<%= player["id"] %>)
      </div>
    <% end %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Current user:</strong>
    <%= current_user.id %>
  </p>
</div>

app/views/games/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing game</h1>

  <%= render "form", game: @game %>

  <%= link_to "Show this game", @game, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/games/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="mb-5">
    <%= link_to 'Home', root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
  </div>

  <% content_for :title, "Games" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Games</h1>
    <%= link_to "New game", new_game_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="games" class="min-w-full">
    <% @games.each do |game| %>
      <%= render game %>
      <p>
        <%= link_to "Show this game", game, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New game</h1>

  <%= render "form", game: @game %>

  <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/games/show.html.erb
<div class="mx-auto w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <div class="w-full flex flex-col aspect-square outline p-3">
      <div id="game-map" class="h-fit grid outline outline-amber-300"></div>
      <div id="game-console" class="p-3 grow h-40 flex flex-col justify-end outline-blue-300 outline overflow-hidden"></div>
      <div class="btn-group h-[12%]  mt-5 flex justify-center">
        <button id="clear-console-btn" type="button" class="py-2 px-3 bg-red-100 rounded-s-lg hover:bg-red-300">
          清除畫面
          <button id="reset-game-btn" type="button" class="py-2 px-3 bg-red-100 hover:bg-red-300">
            重新開始遊戲
          </button>
        </button>
        <button id="get-game-info-btn" type="button" class="py-2 px-3 bg-green-100 hover:bg-green-300">
          目前遊戲狀態
        </button>
        <button id="toggle-game-grid-style-btn" type="button" class="py-2 px-3 bg-amber-100 hover:bg-amber-300">
          切換形狀
        </button>
        <button id="ws-echo-btn" type="button" class="py-2 px-3 bg-amber-100 hover:bg-amber-300">
          Echo
        </button>
        <button id="ws-place-stack-btn" type="button" class="py-2 px-3 bg-amber-100 hover:bg-amber-300">
          放置方塊
        </button>
        <button id="ws-split-stack-btn" type="button" class="py-2 px-3 bg-amber-100 hover:bg-amber-300">
          分配方塊
        </button>
        <button id="initialize-map-btn" type="button" class="py-2 px-3 bg-gray-100 hover:bg-gray-300">
          自動填滿地圖
        </button>
        <button id="place-stack-btn" type="button" class="py-2 px-3 bg-gray-100 hover:bg-gray-300">
          隨機放置方塊
        </button>
        <button id="split-stack-btn" type="button" class="py-2 px-3 bg-gray-100 rounded-e-lg hover:bg-gray-300">
          隨機分配方塊
        </button>
      </div>
    </div>
    <details>
      <summary>show game data</summary>
      <%= render @game %>
    </details>
    <%= link_to "Edit this game", edit_game_path(@game), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to games", games_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium cursor-not-allowed" %>
    <%= link_to "Back to room", room_path(@game.room_id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this game", @game, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>
<style scoped>
  :root {
    --grid-row-count: 7;
  }

  .pasture.hex {
    clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);
    overflow: hidden;
  }

  #game-map {
    > .pasture.hex[data-y="0"] { --grid-row-offset: 0; }
    > .pasture.hex[data-y="1"] { --grid-row-offset: 1; }
    > .pasture.hex[data-y="2"] { --grid-row-offset: 2; }
    > .pasture.hex[data-y="3"] { --grid-row-offset: 3; }
    > .pasture.hex[data-y="4"] { --grid-row-offset: 4; }
    > .pasture.hex[data-y="5"] { --grid-row-offset: 5; }
    > .pasture.hex[data-y="6"] { --grid-row-offset: 6; }
    > .pasture.hex[data-y="7"] { --grid-row-offset: 7; }
    > .pasture.hex[data-y="8"] { --grid-row-offset: 8; }
    > .pasture.hex[data-y="9"] { --grid-row-offset: 9; }
    > .pasture.hex[data-y="10"] { --grid-row-offset: 10; }
  }

  #game-map > .pasture.hex {
    transform: translate(calc(50% * var(--grid-row-offset)), calc(25% * (calc(7 - var(--grid-row-offset)))));
  }

  #game-map:has(.pasture.hex) {
    transform: translate(-12.5%, -12.5%) scale(1.2);
  }

  .pasture.blank { background-color: #dcfce7; }
  .pasture.red { background-color: #fb7185; }
  .pasture.green { background-color: #16a34a; }
  .pasture.blue { background-color: #60a5fa; }
  .pasture.yellow { background-color: #eab308; }
  .pasture.orange { background-color: #f97316; }

  .pasture {
    display: flex;
    justify-content: center;
    align-items: center;
    aspect-ratio: 1/1;
    position: relative;

    &::after {
      content: "(" attr(data-x) " , " attr(data-y) ")";
      position: absolute;
      transform: translateY(20px);
      /* bottom: 0; */
      /* right: 0; */
      font-size: 0.7rem;
      color: #000;
    }
  }
</style>