config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[create index] do
        collection do
          post 'login-as-visitor'
          post 'login-via-gaas-token'
          get 'me-via-gaas-token'
        end
      end
      get 'me', to: 'users#show'
      resource :preferences, only: %i[show update]

      resources :rooms, only: %i[index show create update] do
        member do
          get 'knock-knock', to: 'rooms#knock_knock'
          post 'close', to: 'rooms#destroy'
          post 'game', to: 'games#create'
          delete 'game', to: 'games#destroy'
          post 'game/split', to: 'games#split'
          post 'game/play-unit', to: 'games#play'

          # TODO: will be deprecated
          post 'ai_players', to: 'rooms#bots'

          post 'bots', to: 'rooms#bots'
        end
      end
      resources :games, only: %i[show destroy create] do
        member do
          post 'end-game-via-gaas-token'

          post 'init-map-automatically', to: 'games#init_map_automatically'
          post 'reset-game', to: 'games#reset_game'

          post 'place-stack-automatically', to: 'games#random_place_stack'
          post 'place-stack', to: 'games#place_stack'

          post 'split-stack-automatically', to: 'games#random_split_stack'
          post 'split-stack', to: 'games#split_stack'
        end
      end
      resources :bots, only: %i[create index update destroy show]
    end
  end

  resources :games
  resources :rooms do
    member do
      put :join
      delete :leave
      post :play
    end
  end
  get 'home/index'
  resources :visitors
  get '/login', to: 'sessions#new', as: 'new_user_session'
  post '/login', to: 'sessions#create', as: 'user_session'
  delete '/logout', to: 'sessions#destroy', as: 'destroy_user_session'

  root 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :visitors_rooms, dependent: :destroy
  has_many :players, through: :visitors_rooms, source: :visitor
  has_many :games

  validates :name, presence: true

  COLOR = %w[red blue green yellow].freeze

  # TODO: move to Game model
  def generate_players(seed: 13)
    ret = []
    colors = COLOR.shuffle
    players.rotate(seed).each_with_index do |player, i|
      ret << {
        id: player.id,
        nickname: player.nickname,
        color: colors[i],
        character: player.character,
        role: player.role
      }
    end

    ret
  end

  # TODO: move to Game model
  def start_new_game(seed: nil)
    game = Game.create do |g|
      seed ||= created_at.to_i
      g.room = self
      g.players = generate_players(seed:)
      g.current_player_index = (seed * 13 + 17) % g.players.size
    end

    game.initialize_map_by_system(seed:) if game.should_initialize_map_by_system?
    game
  end

  def closed?
    closed_at.present?
  end

  def call_gaas_end_game(auth0_token)
    room_id = $redis.get("gaas_room_id_of:#{id}")
    return unless room_id

    token_to_close_room = if auth0_token.nil?
                            # use reserve gaas token to call gaas end game
                            $redis.lrange("room:#{id}:gaas_tokens", 0, -1)
                          else
                            [auth0_token]
                          end

    token_to_close_room.each do |token|
      uri = URI("https://api.gaas.waterballsa.tw/rooms/#{room_id}:endGame")
      req = Net::HTTP::Post.new uri
      req['Authorization'] = "Bearer #{token}"
      res = Net::HTTP.start(uri.host, uri.port, use_ssl: true) do |http|
        http.request req
      end
      if res.code.to_i.between?(200, 299)
        $redis.del("gaas_room_id_of:#{id}")
        $redis.del("room:#{id}:gaas_tokens")
        Rails.logger.warn { "Successfully end game #{res.body}" }
        return 0
      else
        # do not raise error, just log it
        Rails.logger.warn { "Failed to end game #{res.body}" }
      end
    end

    Rails.logger.warn { 'Failed to end game' }
  end

  def close
    return nil if closed?

    self.closed_at = Time.current
    self.players = []
    save!
  end

  def ready_to_start?
    players = self.players.reload
    Rails.logger.info { "status: #{status}, players: #{players.size}, all ready: #{players.all?(&:ready?)}" }
    if status == 'waiting' && players.size >= 2 && players.all?(&:ready?)
      Rails.logger.info { 'countdown game start' }
      countdown_game_start
      true
    else
      false
    end
  end

  def start_in_seconds
    $redis.get("room_#{id}:game_start_in_seconds").to_i
  end

  def countdown_game_start(seconds: 5)
    $redis.set("room_#{id}:game_start_in_seconds", seconds)
  end

  def countdown
    Rails.logger.debug("countdown: #{start_in_seconds}")

    return unless start_in_seconds.positive?

    sleep 1

    $redis.decr("room_#{id}:game_start_in_seconds")
  end

  def status
    if games.last&.on_going?
      'playing'
    elsif start_in_seconds.positive?
      'starting'
    else
      'waiting'
    end
  end

  def full?
    players.size >= 4
  end
end

app/controllers/api/v1/rooms_controller.rb
module Api
  module V1
    class RoomsController < BaseController
      before_action :set_room, only: %i[show update destroy bots knock_knock]

      # GET /api/v1/rooms
      def index
        @rooms = Room.where(closed_at: nil).left_outer_joins(:players, :games).distinct.includes(:players, :games)

        render status: :ok
      end

      # GET /api/v1/rooms/:id
      def show
        if @room
          render json: { room: @room }, status: :ok
        else
          render json: { error: 'Room not found' }, status: :not_found
        end
      end

      # POST /api/v1/rooms
      def create
        current_user = Visitor.find(@jwt_request['sub'])
        @room = Room.create!(name: params.fetch(:name, 'New Room'), owner_id: current_user.id)

        Domain::CreateRoomEvent.new(room_id: @room.id).dispatch

        render status: :created
      end

      # DELETE /api/v1/rooms/:id/close
      # 關閉房間
      # https://github.com/side-project-at-SPT/split-rails/issues/10
      # While closing room, call gaas end game if possible
      # situation:
      #   1. room is not hosted by gaas player
      #     => won't call gaas end game
      #   2. room is hosted by gaas player
      #     => api called by gaas player
      #     => call gaas end game
      #   3. room is hosted by gaas player
      #     => api called by non-gaas player
      #     => use reserve gaas token to call gaas end game
      # changes:
      #   when room created, save open_by_gaas in redis if room is hosted via gaas
      #     => save open_by_gaas in redis: type: str, key 'room:#{room.id}:open_by_gaas', value: true/false
      #   when player join room, save gaas_token in redis if room is hosted by gaas player && player is gaas player
      #     => save gaas_token in redis: type: list, key 'room:#{room.id}:gaas_tokens', value: [gaas_token1, gaas_token2, ...]
      #   when close room, call gaas end game if possible
      def destroy
        case result = Domain::SplitRoom::Command::Close.new(room: @room, user_request: @jwt_request).call.error
        in nil then head :ok
        in Domain::SplitRoom::Command::RoomIsRequired
          render json: { error: 'Room not found' }, status: :not_found
        in Domain::SplitRoom::Command::UserIsRequired
          render json: { error: 'User not found' }, status: :unauthorized
        in Domain::SplitRoom::Command::UserIsNotOwner
          render json: { error: 'You are not the owner of this room' }, status: :forbidden
        else render json: { error: result.message }, status: :unprocessable_entity
        end
      end

      # POST /api/v1/rooms/:id/bots
      # Add a random AI player to the room
      # constraints:
      #  1. request user must be in the same room
      def bots
        response_json = {}
        regexp = %r{/api/v1/rooms/\d+/ai_players}
        if request.path.scan(regexp).any?
          response_json[:warning] = '/api/v1/rooms/:id/ai_players is deprecated. Use /api/v1/rooms/:id/bots instead.'
        end

        unless @room
          return render json: response_json.merge(
            { error: 'Room not found' }
          ), status: :not_found
        end

        user = Visitor.find(@jwt_request['sub'])
        unless @room.players.include?(user)
          return render json: response_json.merge({ error: 'You are not in this room' }),
                        status: :unauthorized
        end

        # if room is full, return error
        return render json: response_json.merge({ error: 'Room is full' }), status: :unprocessable_entity if @room.full?

        bot = Bot.online.sample

        # if no bot is online, return
        return render json: response_json.merge({ message: 'No AI player available', room_id: @room.id }) unless bot

        ai_player_id = bot.join_room(@room)

        render json: response_json.merge(
          {
            message: 'AI player added to the room',
            room_id: @room.id,
            ai_player_id:
          }
        )
      end

      def update
        return render json: { error: 'Room not found' }, status: :not_found unless @room

        user = Visitor.find_by(id: @jwt_request['sub'])
        return render json: { error: 'User not found' }, status: :unauthorized unless user

        unless @room.owner_id == user.id
          return render json: { error: 'You are not the owner of this room' },
                        status: :forbidden
        end

        if @room.update(params.require(:room).permit(:name))
          render json: { message: 'Room updated', room_id: @room.id }, status: :ok
        else
          render json: { error: 'Room not updated' }, status: :unprocessable_entity
        end
      end

      # Provide token to subscribe to the room channel
      def knock_knock
        return render json: { error: 'Room not found' }, status: :not_found unless @room

        user = Visitor.find_by(id: @jwt_request['sub'])
        return render json: { error: 'User not found' }, status: :unauthorized unless user

        return render json: { error: 'Room is full' }, status: :unprocessable_entity if @room.full?

        render json: { token: user.knock_knock(@room) }, status: :ok
      end

      private

      def set_room
        @room = Room.find_by(id: params[:id])
      end
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy join leave play ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def join
    if @room.players.include?(current_user)
      redirect_to room_url(@room), notice: "You are already in this room"
      return
    end

    @room.players << current_user
    redirect_to room_url(@room)
  end

  def leave
    @room.players.delete(current_user)
    redirect_to rooms_url
  end

  def play
    # find the last game of the room
    # if the game is finished, create a new game
    # join the game

    game = @room.games.last

    if game.nil? || game.is_finished
      @room.start_new_game
      game = @room.games.last
    end

    redirect_to game_url(game)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "contents") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= room.name %>
    <hr>
    <strong class="block font-medium mb-1">Player:</strong>
    <% room.players.each do |player| %>
      <p class="my-5 list-item ml-5">
        <%= player.name %>
      </p>
    <% end %>
  </p>
  <p class="my-5">
    <%= link_to "開始遊戲", play_room_path(room), data: { turbo_method: :post }, class: "ml-2 rounded-lg py-3 px-5 bg-green-500 inline-block font-medium" if room.players.size >= 2 %>
  </p>
</div>

app/views/rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing room</h1>

  <%= render "form", room: @room %>

  <%= link_to "Show this room", @room, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to rooms", rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/rooms/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="mb-5">
    <%= link_to 'Home', root_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
  </div>
  <% content_for :title, "Rooms" %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Rooms</h1>
    <%= link_to "New room", new_room_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="rooms" class="min-w-full">
    <% @rooms.each do |room| %>
      <%= render room %>
      <p>
        <% if room.players.include?(current_user) %>
          <%= link_to "離開房間", leave_room_path(room), data: { turbo_method: :delete }, class: "ml-2 rounded-lg py-3 px-5 text-white bg-red-600 inline-block font-medium" %>
        <% else %>
          <%= link_to "加入房間", join_room_path(room), data: { turbo_method: :put }, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <% end %>
        <%= link_to "Show this room", room, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New room</h1>

  <%= render "form", room: @room %>

  <%= link_to "Back to rooms", rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/rooms/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @room %>

    <%= link_to "Edit this room", edit_room_path(@room), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to rooms", rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this room", @room, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>